image: node:18

# This command is run before the execution of stages
before_script:
  - npm install

stages:
  - build
  - deploy

# Nombre del job
build:
  stage: build
  script:
    - rm ./package-lock.json
    - npm run build --prod
  artifacts:
    paths:
      - dist/azure-angular/
  only:
    - master


deploy:
  stage: deploy
  script:
    - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - |
      az webapp deployment source config-zip \
        --resource-group grupo-recursos-prueba \
        --name sampleangularazure \
        --src dist.zip
  only:
    - master
